import {getFleet, getAsset, getModelValidation, optimizeMaintenance, simulateAsset} from './api.js?v=8';
import {overviewKpis, plantTopology, healthRanking, renderTelemetry, renderDegradation, telemetryCards, updateRul, riskSummary, riskRows, plannerKpis, gantt, valueComparison, modelValidation, assetDisplay, equipmentTwin} from './render.js?v=8';

const state={fleet:null,selectedAssetId:null,asset:null,riskFilter:'all'};
const titles={overview:['PLANT RELIABILITY','Plant Overview'],asset:['ASSET DIGITAL TWIN','Asset Twin'],risk:['PROGNOSTICS','Failure Risk'],planner:['DECISION OPTIMIZATION','Maintenance Planner'],validation:['MODEL GOVERNANCE','Model Validation']};

function toast(message) { const node=document.getElementById('toast'); node.textContent=message; node.hidden=false; clearTimeout(toast.timer); toast.timer=setTimeout(()=>{node.hidden=true;},3200); }
function setLoading(id,loading) { const button=document.getElementById(id); button.classList.toggle('is-loading',loading); button.disabled=loading; }
function positionTooltip(event) { const tip=document.getElementById('assetTooltip'); const gap=16; const width=tip.offsetWidth || 240; const height=tip.offsetHeight || 170; tip.style.left=`${Math.max(10,Math.min(innerWidth-width-10,event.clientX+gap))}px`; tip.style.top=`${Math.max(10,Math.min(innerHeight-height-10,event.clientY+gap))}px`; }
function showAssetTooltip(assetId,event) { const asset=state.fleet?.assets.find(item=>item.asset_id===assetId); if (!asset) return; const display=assetDisplay(asset); const tip=document.getElementById('assetTooltip'); tip.innerHTML=`<div class="tooltip-top"><div><span>${display.type}</span><strong>${display.tag}</strong></div><i class="risk-badge ${asset.risk_band}">${asset.risk_band}</i></div><div class="tooltip-grid"><div><span>Health</span><strong>${asset.health_score}/100</strong></div><div><span>RUL P50</span><strong>${Math.round(asset.rul.p50)} cycles</strong></div><div><span>Interval</span><strong>${Math.round(asset.rul.p10)}–${Math.round(asset.rul.p90)}</strong></div><div><span>Risk</span><strong>${Math.round(asset.failure_probability*100)}%</strong></div></div><small>Click to open the asset twin</small>`; tip.hidden=false; positionTooltip(event); }
function showSensorTooltip(target,event) { const asset=state.fleet?.assets.find(item=>item.asset_id===target.dataset.assetId); const display=assetDisplay(asset); const tip=document.getElementById('assetTooltip'); tip.innerHTML=`<div class="tooltip-top sensor-tooltip"><div><span>${display.tag} sensor</span><strong>${target.dataset.sensorKey} · ${target.dataset.sensorLabel}</strong></div><i class="sensor-live-dot"></i></div><div class="sensor-reading"><strong>${target.dataset.sensorValue}</strong><span>${target.dataset.sensorUnit}</span></div><small>Current selected-cycle reading</small>`; tip.hidden=false; positionTooltip(event); }
function bindAssetHover() { const selector='.sensor-callout,.machine-group,.twin-asset'; document.addEventListener('pointerover',event=>{ const target=event.target.closest(selector); if (!target || target.contains(event.relatedTarget)) return; if (target.classList.contains('sensor-callout')) showSensorTooltip(target,event); else showAssetTooltip(target.dataset.assetId,event); }); document.addEventListener('pointermove',event=>{ if (!document.getElementById('assetTooltip').hidden && event.target.closest(selector)) positionTooltip(event); }); document.addEventListener('pointerout',event=>{ const target=event.target.closest(selector); if (target && !target.contains(event.relatedTarget)) document.getElementById('assetTooltip').hidden=true; }); }
function selectView(name) { document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('is-active',item.dataset.view===name)); document.querySelectorAll('.view').forEach(view=>{ view.classList.toggle('is-active',view.id===`view-${name}`); if (view.id===`view-${name}`) view.scrollTop=0; }); document.getElementById('pageEyebrow').textContent=titles[name][0]; document.getElementById('pageTitle').textContent=titles[name][1]; history.replaceState(null,'',`#${name}`); if (name==='validation') loadValidation(); if (name==='planner' && !document.getElementById('maintenanceGantt').children.length) runOptimizer(); }
async function selectAsset(assetId, goToTwin=false) { state.selectedAssetId=assetId; document.getElementById('assetSelector').value=assetId; try { state.asset=await getAsset(assetId); renderSelectedAsset(); if (goToTwin) selectView('asset'); } catch (error) { toast(error.message); } }
function renderSelectedAsset() { const asset=state.asset; if (!asset) return; const display=assetDisplay(asset); document.getElementById('telemetryAssetLabel').textContent=display.tag; document.getElementById('sensorTrend').innerHTML=renderTelemetry(asset.telemetry_history); document.getElementById('assetTwinName').textContent=`${display.tag} / ${display.type}`; document.getElementById('engineStage').innerHTML=equipmentTwin(asset); const badge=document.getElementById('assetRiskBadge'); badge.textContent=asset.risk_band.toUpperCase(); badge.className=`risk-badge ${asset.risk_band}`; document.getElementById('assetTelemetryCards').innerHTML=telemetryCards(asset); document.getElementById('estimateSource').textContent=asset.estimate_source; document.getElementById('degradationChart').innerHTML=renderDegradation(asset.telemetry_history,asset.rul); updateRul(asset); }
function bindAssetLinks() { document.querySelectorAll('[data-asset-id]').forEach(node=>node.addEventListener('click',()=>selectAsset(node.dataset.assetId,true))); }
function renderOverview() { const fleet=state.fleet; document.getElementById('overviewKpis').innerHTML=overviewKpis(fleet.kpis); document.getElementById('plantTopology').innerHTML=plantTopology(fleet.assets); document.getElementById('healthRanking').innerHTML=healthRanking(fleet.assets); document.getElementById('riskSummary').innerHTML=riskSummary(fleet.assets); renderRiskTable(); bindAssetLinks(); }
function renderRiskTable() { const assets=state.riskFilter==='attention' ? state.fleet.assets.filter(asset=>asset.risk_band!=='normal') : state.fleet.assets; document.getElementById('riskTableBody').innerHTML=riskRows(assets); bindAssetLinks(); }
function scenarioPayload() { return {load_multiplier:Number(document.getElementById('loadSlider').value),ambient_temperature_delta_c:Number(document.getElementById('tempSlider').value),vibration_multiplier:Number(document.getElementById('vibrationSlider').value),bearing_degradation:Number(document.getElementById('bearingSlider').value)}; }
function updateScenarioLabels() { document.getElementById('loadValue').textContent=`${Number(document.getElementById('loadSlider').value).toFixed(2)}x`; document.getElementById('tempValue').textContent=`${Number(document.getElementById('tempSlider').value).toFixed(0)} C`; document.getElementById('vibrationValue').textContent=`${Number(document.getElementById('vibrationSlider').value).toFixed(2)}x`; document.getElementById('bearingValue').textContent=`${Math.round(Number(document.getElementById('bearingSlider').value)*100)}%`; }
async function runScenario() { if (!state.asset) return; setLoading('runScenario',true); try { const result=await simulateAsset(state.asset.asset_id,scenarioPayload()); document.getElementById('assetTelemetryCards').innerHTML=telemetryCards(state.asset,result.projection.telemetry); document.getElementById('engineStage').innerHTML=equipmentTwin(state.asset,result.projection); updateRul(state.asset,result.projection); const badge=document.getElementById('assetRiskBadge'); badge.textContent=result.projection.risk_band.toUpperCase(); badge.className=`risk-badge ${result.projection.risk_band}`; toast(`Scenario complete. Wear acceleration ${result.projection.wear_acceleration.toFixed(2)}x.`); } catch(error) { toast(error.message); } finally { setLoading('runScenario',false); } }
async function runOptimizer() { if (!state.fleet) return; setLoading('runOptimizer',true); try { const payload={crew_count:Number(document.getElementById('crewCount').value),horizon_slots:Number(document.getElementById('horizonSlots').value),slot_hours:12,risk_tolerance:Number(document.getElementById('riskTolerance').value)}; const result=await optimizeMaintenance(payload); document.getElementById('plannerKpis').innerHTML=plannerKpis(result); document.getElementById('maintenanceGantt').innerHTML=gantt(result,state.fleet.assets); document.getElementById('valueComparison').innerHTML=valueComparison(result); toast(`Optimizer scheduled ${Math.round(result.summary.scheduled_assets)} assets.`); } catch(error) { toast(error.message); } finally { setLoading('runOptimizer',false); } }
async function loadValidation() { try { modelValidation(await getModelValidation()); } catch(error) { toast(error.message); } }
function bindControls() { bindAssetHover(); document.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',()=>selectView(item.dataset.view))); document.getElementById('assetSelector').addEventListener('change',event=>selectAsset(event.target.value,true)); ['loadSlider','tempSlider','vibrationSlider','bearingSlider'].forEach(id=>document.getElementById(id).addEventListener('input',updateScenarioLabels)); document.getElementById('runScenario').addEventListener('click',runScenario); document.getElementById('loadPreset').addEventListener('click',()=>{ document.getElementById('loadSlider').value='1.35';document.getElementById('tempSlider').value='8';updateScenarioLabels();runScenario(); }); document.getElementById('bearingPreset').addEventListener('click',()=>{ document.getElementById('bearingSlider').value='0.65';document.getElementById('vibrationSlider').value='1.75';updateScenarioLabels();runScenario(); }); document.getElementById('resetScenario').addEventListener('click',()=>{ document.getElementById('loadSlider').value='1';document.getElementById('tempSlider').value='0';document.getElementById('vibrationSlider').value='1';document.getElementById('bearingSlider').value='0';updateScenarioLabels();renderSelectedAsset(); }); document.querySelectorAll('[data-risk-filter]').forEach(button=>button.addEventListener('click',()=>{ state.riskFilter=button.dataset.riskFilter; document.querySelectorAll('[data-risk-filter]').forEach(node=>node.classList.toggle('is-active',node===button)); renderRiskTable(); })); document.getElementById('riskTolerance').addEventListener('input',event=>{ document.getElementById('riskToleranceValue').textContent=`${Number(event.target.value).toFixed(2)}x`; }); document.getElementById('runOptimizer').addEventListener('click',runOptimizer); }
function updateClock() { document.getElementById('liveClock').textContent=new Intl.DateTimeFormat([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date()); }
async function init() { bindControls(); updateClock(); setInterval(updateClock,1000); try { state.fleet=await getFleet(); document.getElementById('sourcePill').textContent=state.fleet.source_mode; const selector=document.getElementById('assetSelector'); selector.innerHTML=state.fleet.assets.map(asset=>`<option value="${asset.asset_id}">${assetDisplay(asset).tag} / ${assetDisplay(asset).type}</option>`).join(''); const requested=new URLSearchParams(location.search).get('asset'); state.selectedAssetId=state.fleet.assets.some(asset=>asset.asset_id===requested) ? requested : state.fleet.assets[0]?.asset_id; renderOverview(); if (state.selectedAssetId) await selectAsset(state.selectedAssetId); const initial=location.hash.slice(1); if (titles[initial]) selectView(initial); } catch(error) { toast(error.message); document.getElementById('sourcePill').textContent='Data unavailable'; } }
init();
