import {getFleet, getAsset, getModelValidation, optimizeMaintenance, simulateAsset} from './api.js';
import {overviewKpis, plantTopology, healthRanking, renderTelemetry, renderDegradation, telemetryCards, updateRul, riskSummary, riskRows, plannerKpis, gantt, valueComparison, modelValidation} from './render.js';

const state={fleet:null,selectedAssetId:null,asset:null,riskFilter:'all'};
const titles={overview:['PLANT RELIABILITY','Plant Overview'],asset:['ASSET DIGITAL TWIN','Asset Twin'],risk:['PROGNOSTICS','Failure Risk'],planner:['DECISION OPTIMIZATION','Maintenance Planner'],validation:['MODEL GOVERNANCE','Model Validation']};

function toast(message) { const node=document.getElementById('toast'); node.textContent=message; node.hidden=false; clearTimeout(toast.timer); toast.timer=setTimeout(()=>{node.hidden=true;},3200); }
function selectView(name) { document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('is-active',item.dataset.view===name)); document.querySelectorAll('.view').forEach(view=>view.classList.toggle('is-active',view.id===`view-${name}`)); document.getElementById('pageEyebrow').textContent=titles[name][0]; document.getElementById('pageTitle').textContent=titles[name][1]; if (name==='validation') loadValidation(); if (name==='planner' && !document.getElementById('maintenanceGantt').children.length) runOptimizer(); }
async function selectAsset(assetId, goToTwin=false) { state.selectedAssetId=assetId; document.getElementById('assetSelector').value=assetId; try { state.asset=await getAsset(assetId); renderSelectedAsset(); if (goToTwin) selectView('asset'); } catch (error) { toast(error.message); } }
function renderSelectedAsset() { const asset=state.asset; if (!asset) return; document.getElementById('telemetryAssetLabel').textContent=asset.asset_id; document.getElementById('sensorTrend').innerHTML=renderTelemetry(asset.telemetry_history); document.getElementById('assetTwinName').textContent=`${asset.asset_id} / ${asset.asset_name}`; const badge=document.getElementById('assetRiskBadge'); badge.textContent=asset.risk_band.toUpperCase(); badge.className=`risk-badge ${asset.risk_band}`; document.getElementById('assetTelemetryCards').innerHTML=telemetryCards(asset); document.getElementById('estimateSource').textContent=asset.estimate_source; document.getElementById('degradationChart').innerHTML=renderDegradation(asset.telemetry_history,asset.rul); updateRul(asset); }
function bindAssetLinks() { document.querySelectorAll('[data-asset-id]').forEach(node=>node.addEventListener('click',()=>selectAsset(node.dataset.assetId,true))); }
function renderOverview() { const fleet=state.fleet; document.getElementById('overviewKpis').innerHTML=overviewKpis(fleet.kpis); document.getElementById('plantTopology').innerHTML=plantTopology(fleet.assets); document.getElementById('healthRanking').innerHTML=healthRanking(fleet.assets); document.getElementById('riskSummary').innerHTML=riskSummary(fleet.assets); renderRiskTable(); bindAssetLinks(); }
function renderRiskTable() { const assets=state.riskFilter==='attention' ? state.fleet.assets.filter(asset=>asset.risk_band!=='normal') : state.fleet.assets; document.getElementById('riskTableBody').innerHTML=riskRows(assets); bindAssetLinks(); }
function scenarioPayload() { return {load_multiplier:Number(document.getElementById('loadSlider').value),ambient_temperature_delta_c:Number(document.getElementById('tempSlider').value),vibration_multiplier:Number(document.getElementById('vibrationSlider').value),bearing_degradation:Number(document.getElementById('bearingSlider').value)}; }
function updateScenarioLabels() { document.getElementById('loadValue').textContent=`${Number(document.getElementById('loadSlider').value).toFixed(2)}x`; document.getElementById('tempValue').textContent=`${Number(document.getElementById('tempSlider').value).toFixed(0)} C`; document.getElementById('vibrationValue').textContent=`${Number(document.getElementById('vibrationSlider').value).toFixed(2)}x`; document.getElementById('bearingValue').textContent=`${Math.round(Number(document.getElementById('bearingSlider').value)*100)}%`; }
async function runScenario() { if (!state.asset) return; try { const result=await simulateAsset(state.asset.asset_id,scenarioPayload()); document.getElementById('assetTelemetryCards').innerHTML=telemetryCards(state.asset,result.projection.telemetry); updateRul(state.asset,result.projection); const badge=document.getElementById('assetRiskBadge'); badge.textContent=result.projection.risk_band.toUpperCase(); badge.className=`risk-badge ${result.projection.risk_band}`; toast(`Scenario complete. Wear acceleration ${result.projection.wear_acceleration.toFixed(2)}x.`); } catch(error) { toast(error.message); } }
async function runOptimizer() { try { const payload={crew_count:Number(document.getElementById('crewCount').value),horizon_slots:Number(document.getElementById('horizonSlots').value),slot_hours:12,risk_tolerance:Number(document.getElementById('riskTolerance').value)}; const result=await optimizeMaintenance(payload); document.getElementById('plannerKpis').innerHTML=plannerKpis(result); document.getElementById('maintenanceGantt').innerHTML=gantt(result,state.fleet.assets); document.getElementById('valueComparison').innerHTML=valueComparison(result); toast(`Optimizer scheduled ${Math.round(result.summary.scheduled_assets)} assets.`); } catch(error) { toast(error.message); } }
async function loadValidation() { try { modelValidation(await getModelValidation()); } catch(error) { toast(error.message); } }
function bindControls() { document.querySelectorAll('.nav-item').forEach(item=>item.addEventListener('click',()=>selectView(item.dataset.view))); document.getElementById('assetSelector').addEventListener('change',event=>selectAsset(event.target.value,true)); ['loadSlider','tempSlider','vibrationSlider','bearingSlider'].forEach(id=>document.getElementById(id).addEventListener('input',updateScenarioLabels)); document.getElementById('runScenario').addEventListener('click',runScenario); document.getElementById('loadPreset').addEventListener('click',()=>{ document.getElementById('loadSlider').value='1.35';document.getElementById('tempSlider').value='8';updateScenarioLabels();runScenario(); }); document.getElementById('bearingPreset').addEventListener('click',()=>{ document.getElementById('bearingSlider').value='0.65';document.getElementById('vibrationSlider').value='1.75';updateScenarioLabels();runScenario(); }); document.getElementById('resetScenario').addEventListener('click',()=>{ document.getElementById('loadSlider').value='1';document.getElementById('tempSlider').value='0';document.getElementById('vibrationSlider').value='1';document.getElementById('bearingSlider').value='0';updateScenarioLabels();renderSelectedAsset(); }); document.querySelectorAll('[data-risk-filter]').forEach(button=>button.addEventListener('click',()=>{ state.riskFilter=button.dataset.riskFilter; document.querySelectorAll('[data-risk-filter]').forEach(node=>node.classList.toggle('is-active',node===button)); renderRiskTable(); })); document.getElementById('riskTolerance').addEventListener('input',event=>{ document.getElementById('riskToleranceValue').textContent=`${Number(event.target.value).toFixed(2)}x`; }); document.getElementById('runOptimizer').addEventListener('click',runOptimizer); }
async function init() { bindControls(); try { state.fleet=await getFleet(); document.getElementById('sourcePill').textContent=state.fleet.source_mode; const selector=document.getElementById('assetSelector'); selector.innerHTML=state.fleet.assets.map(asset=>`<option value="${asset.asset_id}">${asset.asset_id} / ${asset.cell}</option>`).join(''); state.selectedAssetId=state.fleet.assets[0]?.asset_id; renderOverview(); if (state.selectedAssetId) await selectAsset(state.selectedAssetId); } catch(error) { toast(error.message); document.getElementById('sourcePill').textContent='Data unavailable'; } }
init();
